package assignment5;
import java.util.Random;

public class q1 {
    public static void main(String[] args) {
        producerThreadNew producer = new producerThreadNew("Producer");
        consumerThreadNew consumer = new consumerThreadNew("Consumer", producer);
    }
}
class producerThreadNew implements Runnable {
    String name;
    Thread t;
    int n;
    boolean numberGenerated = false;

    producerThreadNew(String threadName) {
        this.name = threadName;
        t = new Thread(this, name);
        System.out.println("New producer thread: " + t);
        t.start();
    }

    public void run() {
        Random random = new Random();
        n = random.nextInt(1000); // Generates a number between 0 and 999
        System.out.println("Number generated by Producer: " + n);
        numberGenerated = true;

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            System.out.println("Producer thread interrupted.");
        }
    }

    public int getNumber() {
        return n;
    }

    public boolean isNumberGenerated() {
        return numberGenerated;
    }
}

class consumerThreadNew implements Runnable {
    String name;
    Thread t;
    producerThreadNew producer;

    consumerThreadNew(String threadName, producerThreadNew producer) {
        this.name = threadName;
        this.producer = producer;
        t = new Thread(this, name);
        System.out.println("New consumer thread: " + t);
        t.start();
    }

    public void run() {
        while (!producer.isNumberGenerated()) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                System.out.println("Consumer thread interrupted.");
            }
        }

        int number = producer.getNumber();
        System.out.println("Number in words by Consumer: " + numberToWords(number));
    }

    private String numberToWords(int number) {
        if (number == 0) return "zero";

        String[] units = {"", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"};
        String[] teens = {"", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"};
        String[] tens = {"", "ten", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"};
        String[] hundreds = {"", "one hundred", "two hundred", "three hundred", "four hundred", "five hundred", "six hundred", "seven hundred", "eight hundred", "nine hundred"};

        StringBuilder words = new StringBuilder();

        if (number >= 100) {
            words.append(hundreds[number / 100]).append(" ");
            number %= 100;
        }

        if (number >= 20) {
            words.append(tens[number / 10]).append(" ");
            number %= 10;
        } else if (number > 10) {
            words.append(teens[number - 10]).append(" ");
            number = 0;
        } else if (number == 10) {
            words.append(tens[1]).append(" ");
            number = 0;
        }

        if (number > 0) {
            words.append(units[number]);
        }

        return words.toString().trim();
    }
}

